; Dragon Warrior IV (NES) - Main Initialization
; Auto-generated by extended_disassembler.py
; ============================================

; PRG-ROM: 524288 bytes
; Mapper: 1

; RESET: $FFD8
; NMI:   $0502
; IRQ:   $C408

  $C000  FF            .db  $FF
  $C001  4C 77 E5      JMP  $E577
  $C004  4C 4B E5      JMP  $E54B
  $C007  4C 8D E5      JMP  $E58D
  $C00A  4C A3 E5      JMP  $E5A3
  $C00D  4C B9 E5      JMP  $E5B9
  $C010  4C CF E5      JMP  $E5CF
  $C013  4C E5 E5      JMP  $E5E5
  $C016  4C 61 E5      JMP  $E561
  $C019  4C 87 E6      JMP  $E687
  $C01C  4C 8A F0      JMP  $F08A
  $C01F  4C 5B EF      JMP  $EF5B
  $C022  4C 57 F0      JMP  $F057
  $C025  4C 5E F0      JMP  $F05E
  $C028  4C D5 EE      JMP  $EED5
  $C02B  4C B4 F0      JMP  $F0B4
  $C02E  4C FB E5      JMP  $E5FB
  $C031  4C 17 E6      JMP  $E617
  $C034  4C 2D E6      JMP  $E62D
  $C037  4C 43 E6      JMP  $E643
  $C03A  4C 59 E6      JMP  $E659

Main_Init:
  $C03D  D8            CLD  
  $C03E  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C041  10 FB         BPL  $C04E
  $C043  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C046  10 FB         BPL  $C053
  $C048  EA            NOP  
  $C049  EA            NOP  
  $C04A  EA            NOP  
  $C04B  EA            NOP  
  $C04C  EA            NOP  
  $C04D  EA            NOP  
  $C04E  A9 10         LDA  #$10
  $C050  8D 00 20      STA  PPUCTRL  ; PPUCTRL
  $C053  A9 00         LDA  #$00
  $C055  8D 01 20      STA  PPUMASK  ; PPUMASK
  $C058  8D FF FF      STA  $FFFF
  $C05B  8D FF FF      STA  $FFFF
  $C05E  8D FF FF      STA  $FFFF
  $C061  8D FF FF      STA  $FFFF
  $C064  8D FF FF      STA  $FFFF
  $C067  A9 4C         LDA  #$4C
  $C069  8D 02 05      STA  nmi_jmp
  $C06C  AD D2 C0      LDA  $C0D2
  $C06F  8D 03 05      STA  nmi_handler_lo
  $C072  AD D3 C0      LDA  $C0D3
  $C075  8D 04 05      STA  nmi_handler_hi
  $C078  A2 FF         LDX  #$FF
  $C07A  9A            TXS  
  $C07B  A9 00         LDA  #$00
  $C07D  AA            TAX  
  $C07E  95 00         STA  $00,X
  $C080  9D 00 03      STA  $0300,X
  $C083  9D 00 04      STA  $0400,X
  $C086  9D 05 05      STA  $0505,X
  $C089  9D 00 06      STA  $0600,X
  $C08C  9D 00 07      STA  $0700,X
  $C08F  E8            INX  
  $C090  D0 EC         BNE  $C08E
  $C092  A9 0E         LDA  #$0E
  $C094  8D 00 05      STA  mmc_bank_select
  $C097  A9 10         LDA  #$10
  $C099  8D 01 05      STA  mmc_bank_data
  $C09C  85 39         STA  $39
  $C09E  20 04 C1      JSR  Sub_C104
  $C0A1  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C0A4  A9 10         LDA  #$10
  $C0A6  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C0A9  A9 00         LDA  #$00
  $C0AB  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C0AE  A2 10         LDX  #$10
  $C0B0  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C0B3  CA            DEX  
  $C0B4  D0 FA         BNE  $C0C0
  $C0B6  A9 90         LDA  #$90
  $C0B8  8D 05 05      STA  $0505
  $C0BB  8D 00 20      STA  PPUCTRL  ; PPUCTRL
  $C0BE  20 69 C5      JSR  $C569
  $C0C1  20 43 C5      JSR  $C543
  $C0C4  20 74 FF      JSR  $FF74
  $C0C7  A9 18         LDA  #$18
  $C0C9  8D 06 05      STA  $0506
  $C0CC  8D 01 20      STA  PPUMASK  ; PPUMASK
  $C0CF  4C 68 C9      JMP  $C968
  $C0D2  5A            .db  $5A
  $C0D3  C1 AD         CMP  ($AD,X)
  $C0D5  02            .db  $02
  $C0D6  20 10 FB      JSR  $FB10
  $C0D9  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C0DC  30 FB         BMI  $C0E9
  $C0DE  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C0E1  10 FB         BPL  $C0EE
  $C0E3  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C0E6  30 FB         BMI  $C0F3
  $C0E8  60            RTS  
  $C0E9  A9 40         LDA  #$40
  $C0EB  8D 02 05      STA  nmi_jmp
  $C0EE  A9 00         LDA  #$00
  $C0F0  8D FF FF      STA  $FFFF
  $C0F3  8D FF FF      STA  $FFFF
  $C0F6  8D FF FF      STA  $FFFF
  $C0F9  8D FF FF      STA  $FFFF
  $C0FC  A9 01         LDA  #$01
  $C0FE  8D FF FF      STA  $FFFF
  $C101  4C 01 C1      JMP  $C101

Sub_C104:
  $C104  EE DF FF      INC  $FFDF
  $C107  AD 00 05      LDA  mmc_bank_select
  $C10A  20 18 C1      JSR  $C118
  $C10D  AD 01 05      LDA  mmc_bank_data
  $C110  20 2F C1      JSR  $C12F
  $C113  A9 00         LDA  #$00
  $C115  4C 46 C1      JMP  $C146
  $C118  8D 00 05      STA  mmc_bank_select
  $C11B  8D FF 9F      STA  $9FFF
  $C11E  4A            LSR  
  $C11F  8D FF 9F      STA  $9FFF
  $C122  4A            LSR  
  $C123  8D FF 9F      STA  $9FFF
  $C126  4A            LSR  
  $C127  8D FF 9F      STA  $9FFF
  $C12A  4A            LSR  
  $C12B  8D FF 9F      STA  $9FFF
  $C12E  60            RTS  
  $C12F  8D 01 05      STA  mmc_bank_data
  $C132  8D FF BF      STA  $BFFF
  $C135  4A            LSR  
  $C136  8D FF BF      STA  $BFFF
  $C139  4A            LSR  
  $C13A  8D FF BF      STA  $BFFF
  $C13D  4A            LSR  
  $C13E  8D FF BF      STA  $BFFF
  $C141  4A            LSR  
  $C142  8D FF BF      STA  $BFFF
  $C145  60            RTS  
  $C146  8D FF DF      STA  $DFFF
  $C149  4A            LSR  
  $C14A  8D FF DF      STA  $DFFF
  $C14D  4A            LSR  
  $C14E  8D FF DF      STA  $DFFF
  $C151  4A            LSR  
  $C152  8D FF DF      STA  $DFFF
  $C155  4A            LSR  
  $C156  8D FF DF      STA  $DFFF
  $C159  60            RTS  
  $C15A  48            PHA  
  $C15B  8A            TXA  
  $C15C  48            PHA  
  $C15D  98            TYA  
  $C15E  48            PHA  
  $C15F  A5 1F         LDA  $1F
  $C161  30 1E         BMI  $C191
  $C163  BA            TSX  
  $C164  BC 06 01      LDY  $0106,X
  $C167  C8            INY  
  $C168  D0 17         BNE  $C191
  $C16A  BD 05 01      LDA  $0105,X
  $C16D  C9 77         CMP  #$77
  $C16F  90 10         BCC  $C191
  $C171  C9 81         CMP  #$81
  $C173  B0 0C         BCS  $C191
  $C175  AD 02 20      LDA  PPUSTATUS  ; PPUSTATUS
  $C178  20 22 C2      JSR  $C222
  $C17B  20 03 C3      JSR  $C303
  $C17E  20 EA C2      JSR  $C2EA
  $C181  BA            TSX  
  $C182  BC 06 01      LDY  $0106,X
  $C185  C8            INY  
  $C186  D0 13         BNE  $C1AB
  $C188  BD 05 01      LDA  $0105,X
  $C18B  C9 AB         CMP  #$AB
  $C18D  90 0C         BCC  $C1AB
  $C18F  C9 D6         CMP  #$D6
  $C191  B0 08         BCS  $C1AB
  $C193  A9 D6         LDA  #$D6
  $C195  9D 05 01      STA  $0105,X
  $C198  20 04 C1      JSR  Sub_C104
  $C19B  AD 19 05      LDA  $0519
  $C19E  D0 10         BNE  $C1C0
  $C1A0  EE 21 C2      INC  $C221
  $C1A3  A9 10         LDA  #$10
  $C1A5  20 2F C1      JSR  $C12F
  $C1A8  A9 10         LDA  #$10
  $C1AA  20 2F C1      JSR  $C12F
  $C1AD  20 19 C0      JSR  $C019
  $C1B0  AD 07 05      LDA  $0507
  $C1B3  20 91 FF      JSR  $FF91
  $C1B6  EA            NOP  
  $C1B7  EA            NOP  
  $C1B8  EA            NOP  
  $C1B9  EA            NOP  
  $C1BA  EA            NOP  
  $C1BB  EA            NOP  
  $C1BC  EA            NOP  
  $C1BD  BA            TSX  
  $C1BE  BD 06 01      LDA  $0106,X
  $C1C1  C9 6C         CMP  #$6C
  $C1C3  D0 2A         BNE  $C1FF
  $C1C5  BD 05 01      LDA  $0105,X
  $C1C8  C9 B9         CMP  #$B9
  $C1CA  90 11         BCC  $C1ED
  $C1CC  C9 D6         CMP  #$D6
  $C1CE  B0 0D         BCS  $C1ED
  $C1D0  A9 D6         LDA  #$D6
  $C1D2  9D 05 01      STA  $0105,X
  $C1D5  A9 00         LDA  #$00
  $C1D7  20 2F C1      JSR  $C12F
  $C1DA  4C EF C1      JMP  $C1EF
  $C1DD  C9 E9         CMP  #$E9
  $C1DF  90 0E         BCC  $C1FF
  $C1E1  C9 FF         CMP  #$FF
  $C1E3  B0 0A         BCS  $C1FF
  $C1E5  A9 FF         LDA  #$FF
  $C1E7  9D 05 01      STA  $0105,X
  $C1EA  A9 10         LDA  #$10
  $C1EC  20 2F C1      JSR  $C12F
  $C1EF  EE 0C 05      INC  $050C
  $C1F2  BA            TSX  
  $C1F3  BD 05 01      LDA  $0105,X
  $C1F6  85 10         STA  $10
  $C1F8  BD 06 01      LDA  $0106,X
  $C1FB  85 11         STA  $11
  $C1FD  A0 00         LDY  #$00
  $C1FF  B1 10         LDA  ($10),Y
  $C201  29 0F         AND  #$0F
  $C203  C9 07         CMP  #$07
  $C205  F0 12         BEQ  $C229
  $C207  C9 0F         CMP  #$0F
  $C209  F0 0E         BEQ  $C229
  $C20B  C9 03         CMP  #$03
  $C20D  F0 0A         BEQ  $C229
  $C20F  C9 0B         CMP  #$0B
  $C211  F0 06         BEQ  $C229
  $C213  68            PLA  
  $C214  A8            TAY  
  $C215  68            PLA  
  $C216  AA            TAX  
  $C217  68            PLA  
  $C218  40            RTI  
  $C219  68            PLA  
  $C21A  A8            TAY  
  $C21B  68            PLA  
  $C21C  AA            TAX  
  $C21D  68            PLA  
  $C21E  4C 08 C4      JMP  $C408
  $C221  80            .db  $80
  $C222  A5 1F         LDA  $1F
  $C224  29 20         AND  #$20
  $C226  D0 12         BNE  $C24A
  $C228  A5 1F         LDA  $1F
  $C22A  29 10         AND  #$10
  $C22C  F0 03         BEQ  $C241
  $C22E  4C 97 C2      JMP  $C297
  $C231  A5 1F         LDA  $1F
  $C233  29 04         AND  #$04
  $C235  F0 3F         BEQ  $C286
  $C237  4C 15 C3      JMP  $C315
  $C23A  A2 00         LDX  #$00
  $C23C  AD 0B 05      LDA  $050B
  $C23F  F0 35         BEQ  $C286
  $C241  A0 01         LDY  #$01
  $C243  BD 00 03      LDA  $0300,X
  $C246  10 14         BPL  $C26C
  $C248  A8            TAY  
  $C249  4A            LSR  
  $C24A  4A            LSR  
  $C24B  4A            LSR  
  $C24C  4A            LSR  
  $C24D  29 04         AND  #$04
  $C24F  0D 05 05      ORA  $0505
  $C252  8D 00 20      STA  PPUCTRL  ; PPUCTRL
  $C255  98            TYA  
  $C256  E8            INX  
  $C257  BC 00 03      LDY  $0300,X
  $C25A  29 3F         AND  #$3F
  $C25C  E8            INX  
  $C25D  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C260  BD 00 03      LDA  $0300,X
  $C263  E8            INX  
  $C264  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C267  BD 00 03      LDA  $0300,X
  $C26A  E8            INX  
  $C26B  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C26E  88            DEY  
  $C26F  D0 F6         BNE  $C277
  $C271  CE 0B 05      DEC  $050B
  $C274  D0 CB         BNE  $C251
  $C276  AD 06 05      LDA  $0506
  $C279  29 08         AND  #$08
  $C27B  F0 19         BEQ  $C2A6
  $C27D  A9 3F         LDA  #$3F
  $C27F  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C282  A9 00         LDA  #$00
  $C284  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C287  8D 0A 05      STA  $050A
  $C28A  AD FC 05      LDA  $05FC
  $C28D  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C290  A5 1F         LDA  $1F
  $C292  29 DF         AND  #$DF
  $C294  85 1F         STA  $1F
  $C296  60            RTS  
  $C297  A2 00         LDX  #$00
  $C299  BD 00 03      LDA  $0300,X
  $C29C  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C29F  BD 01 03      LDA  $0301,X
  $C2A2  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C2A5  48            PHA  
  $C2A6  BD 02 03      LDA  $0302,X
  $C2A9  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C2AC  BD 03 03      LDA  $0303,X
  $C2AF  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C2B2  BD 00 03      LDA  $0300,X
  $C2B5  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C2B8  68            PLA  
  $C2B9  18            CLC  
  $C2BA  69 20         ADC  #$20
  $C2BC  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C2BF  BD 04 03      LDA  $0304,X
  $C2C2  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C2C5  BD 05 03      LDA  $0305,X
  $C2C8  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C2CB  BD 06 03      LDA  $0306,X
  $C2CE  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C2D1  BD 07 03      LDA  $0307,X
  $C2D4  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C2D7  BD 08 03      LDA  $0308,X
  $C2DA  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C2DD  8A            TXA  
  $C2DE  18            CLC  
  $C2DF  69 09         ADC  #$09
  $C2E1  AA            TAX  
  $C2E2  CE 0B 05      DEC  $050B
  $C2E5  D0 B2         BNE  $C2A9
  $C2E7  4C 76 C2      JMP  $C276
  $C2EA  AD 05 05      LDA  $0505
  $C2ED  8D 00 20      STA  PPUCTRL  ; PPUCTRL
  $C2F0  AD 06 05      LDA  $0506
  $C2F3  8D 01 20      STA  PPUMASK  ; PPUMASK
  $C2F6  AD 08 05      LDA  $0508
  $C2F9  8D 05 20      STA  PPUSCROLL  ; PPUSCROLL
  $C2FC  AD 09 05      LDA  $0509
  $C2FF  8D 05 20      STA  PPUSCROLL  ; PPUSCROLL
  $C302  60            RTS  
  $C303  24 1F         BIT  $1F
  $C305  70 0D         BVS  $C324
  $C307  AD 06 05      LDA  $0506
  $C30A  09 18         ORA  #$18
  $C30C  8D 01 20      STA  PPUMASK  ; PPUMASK
  $C30F  A9 02         LDA  #$02
  $C311  8D 14 40      STA  OAMDMA  ; OAMDMA
  $C314  60            RTS  
  $C315  AE 1A 05      LDX  $051A
  $C318  BD 7B C3      LDA  $C37B,X
  $C31B  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C31E  E8            INX  
  $C31F  BD 7B C3      LDA  $C37B,X
  $C322  8D 06 20      STA  PPUADDR  ; PPUADDR
  $C325  E8            INX  
  $C326  A9 00         LDA  #$00
  $C328  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C32B  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C32E  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C331  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C334  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C337  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C33A  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C33D  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C340  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C343  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C346  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C349  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C34C  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C34F  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C352  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C355  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C358  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C35B  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C35E  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C361  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C364  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C367  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C36A  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C36D  8D 07 20      STA  PPUDATA  ; PPUDATA
  $C370  E0 10         CPX  #$10
  $C372  90 A4         BCC  $C328
  $C374  A5 1F         LDA  $1F
  $C376  29 FB         AND  #$FB
  $C378  85 1F         STA  $1F
  $C37A  60            RTS  
  $C37B  22            .db  $22
  $C37C  64            .db  $64
  $C37D  22            .db  $22
  $C37E  84 22         STY  $22
  $C380  A4 22         LDY  $22
  $C382  C4 22         CPY  $22
  $C384  E4 23         CPX  $23
  $C386  04            .db  $04
  $C387  23            .db  $23
  $C388  24 23         BIT  $23
  $C38A  44            .db  $44
  $C38B  85 20         STA  $20
  $C38D  86 21         STX  $21
  $C38F  AD 07 05      LDA  $0507
  $C392  48            PHA  
  $C393  08            PHP  
  $C394  AD 07 05      LDA  $0507
  $C397  8D 17 05      STA  $0517
  $C39A  20 BA C3      JSR  $C3BA
  $C39D  A9 4C         LDA  #$4C
  $C39F  85 23         STA  $23
  $C3A1  A6 21         LDX  $21
  $C3A3  A5 20         LDA  $20
  $C3A5  28            PLP  
  $C3A6  20 23 00      JSR  $0023
  $C3A9  08            PHP  
  $C3AA  85 20         STA  $20
  $C3AC  68            PLA  
  $C3AD  85 23         STA  $23
  $C3AF  68            PLA  
  $C3B0  20 91 FF      JSR  $FF91
  $C3B3  A5 23         LDA  $23
  $C3B5  48            PHA  
  $C3B6  A5 20         LDA  $20
  $C3B8  28            PLP  
  $C3B9  60            RTS  
  $C3BA  A5 23         LDA  $23
  $C3BC  20 91 FF      JSR  $FF91
  $C3BF  A5 24         LDA  $24
  $C3C1  0A            ASL  
  $C3C2  AA            TAX  
  $C3C3  BD 00 80      LDA  $8000,X
  $C3C6  85 24         STA  $24
  $C3C8  BD 01 80      LDA  $8001,X
  $C3CB  85 25         STA  $25
  $C3CD  60            RTS  
  $C3CE  85 20         STA  $20
  $C3D0  86 21         STX  $21
  $C3D2  AD 07 05      LDA  $0507
  $C3D5  48            PHA  
  $C3D6  20 BA C3      JSR  $C3BA
  $C3D9  68            PLA  
  $C3DA  20 91 FF      JSR  $FF91
  $C3DD  A6 21         LDX  $21
  $C3DF  A5 24         LDA  $24
  $C3E1  95 00         STA  $00,X
  $C3E3  A5 25         LDA  $25
  $C3E5  95 01         STA  $01,X
  $C3E7  A5 20         LDA  $20
  $C3E9  60            RTS  
  $C3EA  85 20         STA  $20
  $C3EC  AD 07 05      LDA  $0507
  $C3EF  48            PHA  
  $C3F0  A5 20         LDA  $20
  $C3F2  20 91 FF      JSR  $FF91
  $C3F5  B5 00         LDA  $00,X
  $C3F7  85 23         STA  $23
  $C3F9  B5 01         LDA  $01,X
  $C3FB  85 24         STA  $24
  $C3FD  B1 23         LDA  ($23),Y
  $C3FF  85 20         STA  $20
