; Dragon Warrior IV (NES) - Interrupt Vector Handlers
; Auto-generated by disassembler.py
; ============================================

; PRG-ROM: 524288 bytes
; Mapper: 1

; NMI Vector:   $0502
; RESET Vector: $FFD8
; IRQ Vector:   $C408

; ============================================
; RESET HANDLER
; ============================================
  $FFD8  78            SEI  
  $FFD9  EE DF FF      INC  $FFDF
  $FFDC  4C 3D C0      JMP  $C03D

  ; Jump to $C03D
  $C03D  D8            CLD  
  $C03E  AD 02 20      LDA  $2002
  $C041  10 FB         BPL  $803E
  $C043  AD 02 20      LDA  $2002
  $C046  10 FB         BPL  $8043
  $C048  EA            NOP  
  $C049  EA            NOP  
  $C04A  EA            NOP  
  $C04B  EA            NOP  
  $C04C  EA            NOP  
  $C04D  EA            NOP  
  $C04E  A9 10         LDA  #$10
  $C050  8D 00 20      STA  $2000
  $C053  A9 00         LDA  #$00
  $C055  8D 01 20      STA  $2001
  $C058  8D FF FF      STA  $FFFF
  $C05B  8D FF FF      STA  $FFFF
  $C05E  8D FF FF      STA  $FFFF
  $C061  8D FF FF      STA  $FFFF
  $C064  8D FF FF      STA  $FFFF
  $C067  A9 4C         LDA  #$4C
  $C069  8D 02 05      STA  NMI_Handler
  $C06C  AD D2 C0      LDA  $C0D2
  $C06F  8D 03 05      STA  $0503
  $C072  AD D3 C0      LDA  $C0D3
  $C075  8D 04 05      STA  $0504
  $C078  A2 FF         LDX  #$FF
  $C07A  9A            TXS  
  $C07B  A9 00         LDA  #$00
  $C07D  AA            TAX  
  $C07E  95 00         STA  $00,X
  $C080  9D 00 03      STA  $0300,X
  $C083  9D 00 04      STA  $0400,X
  $C086  9D 05 05      STA  $0505,X
  $C089  9D 00 06      STA  $0600,X
  $C08C  9D 00 07      STA  $0700,X
  $C08F  E8            INX  
  $C090  D0 EC         BNE  $807E
  $C092  A9 0E         LDA  #$0E
  $C094  8D 00 05      STA  $0500
  $C097  A9 10         LDA  #$10
  $C099  8D 01 05      STA  $0501
  $C09C  85 39         STA  $39
  $C09E  20 04 C1      JSR  $C104
  $C0A1  AD 02 20      LDA  $2002
  $C0A4  A9 10         LDA  #$10
  $C0A6  8D 06 20      STA  $2006
