; Dragon Warrior IV (NES) - Text Engine Disassembly
; ================================================
; Bank 22 ($16) - Text rendering and compression
; Generated by export_asm.py
;
; Text encoding:
;   $00	  = Space
;   $01-$0A  = Digits 0-9
;   $0B-$24  = Lowercase a-z
;   $25-$3E  = Uppercase A-Z
;   $80-$FE  = DTE pairs (dictionary compression)
;   $FD	  = LINE (newline)
;   $FE	  = CTRL (PPU positioning)
;   $FF	  = END (terminator)
;

; === ZERO PAGE EQUATES ===
zp_temp_00		   = $00
zp_temp_04		   = $04
zp_loop_counter	  = $0D
text_state_5C		= $5C
text_counter_60	  = $60
text_ptr_lo		  = $EE
text_ptr_hi		  = $EF
text_offset		  = $F0
text_flags_F5		= $F5
current_char_raw	 = $F6
text_param		   = $F7
current_char		 = $F8

; === RAM EQUATES ===
text_var_03C8		= $03C8
text_var_03C9		= $03C9
text_var_03CB		= $03CB
text_state		   = $03D3
text_ppu_addr		= $03D4
text_flags		   = $03D5
text_x_pos		   = $03D6
text_y_pos		   = $03D7
text_line_ctr		= $03D9
text_window_id	   = $03DB
text_var_03E1		= $03E1
text_buffer		  = $03E3
text_array_04E0	  = $04E0
text_var_04F2		= $04F2
text_var_04F3		= $04F3
current_bank		 = $0507
text_bank			= $0517
buffer_0553		  = $0553
buffer_0554		  = $0554
text_ptr_table	   = $076C
text_ptr_table_hi	= $076D
input_flags		  = $07B4

; ============================================
; SECTION 1: DTE HANDLER ($8270-$82E0)
; ============================================
;
; DTE check: bytes >= $80 are compressed
; Low 3 bits = dictionary index
;

	LSR  $83,X				 ; $8270: 56 83
check_dte:
	CMP  #$80				  ; $8272: C9 80
	BCS  dte_handler		   ; $8274: B0 24
	AND  #$0F				  ; $8276: 29 0F
	TAX						; $8278: AA
	BRK						; $8279: 00
	ROL						; $827A: 2A
	.byte $53					; $827B
	LDX  #$00				  ; $827C: A2 00
	LDA  text_buffer,X		 ; $827E: BD E3 03
	STA  buffer_0554,X		 ; $8281: 9D 54 05
	INX						; $8284: E8
	CPX  #$08				  ; $8285: E0 08
	BNE  $827E				 ; $8287: D0 F5
	LDA  buffer_0553,X		 ; $8289: BD 53 05
	BNE  $8292				 ; $828C: D0 04
	DEX						; $828E: CA
	JMP  $8289				 ; $828F: 4C 89 82
	LDA  #$40				  ; $8292: A9 40
	STA  buffer_0554,X		 ; $8294: 9D 54 05
	JMP  text_process_next	 ; $8297: 4C 36 83
dte_handler:
	PHA						; $829A: 48
	AND  #$07				  ; $829B: 29 07
	TAX						; $829D: AA
	BRK						; $829E: 00
	AND  #$C3				  ; $829F: 29 C3
	.byte $0C					; $82A1
	BCC  $82DB				 ; $82A2: 90 37
	BRK						; $82A4: 00
	.byte $67					; $82A5
	.byte $73					; $82A6
	TAX						; $82A7: AA
	BRK						; $82A8: 00
	ROL						; $82A9: 2A
	.byte $53					; $82AA
	LDX  #$00				  ; $82AB: A2 00
	LDA  text_buffer,X		 ; $82AD: BD E3 03
	STA  buffer_0554,X		 ; $82B0: 9D 54 05
	INX						; $82B3: E8
	CPX  #$08				  ; $82B4: E0 08
	BNE  $82AD				 ; $82B6: D0 F5
	LDA  buffer_0553,X		 ; $82B8: BD 53 05
	BNE  $82C1				 ; $82BB: D0 04
	DEX						; $82BD: CA
	JMP  $82B8				 ; $82BE: 4C B8 82
	LDY  #$09				  ; $82C1: A0 09
	LDA  dte_data_table,Y	  ; $82C3: B9 D1 82
	STA  buffer_0554,X		 ; $82C6: 9D 54 05
	INX						; $82C9: E8
	DEY						; $82CA: 88
	BPL  $82C3				 ; $82CB: 10 F6
	PLA						; $82CD: 68
	JMP  text_process_next	 ; $82CE: 4C 36 83
dte_data_table:
	RTI						; $82D1: 40
	.byte $0F					; $82D2
	ASL  $0C,X				 ; $82D3: 16 0C
	.byte $1F					; $82D5
	ORA  $0028,Y			   ; $82D6: 19 28 00
	ORA  $006B,X			   ; $82D9: 1D 6B 00
	AND  $AAB3				 ; $82DC: 2D B3 AA
	LDA  $6E45,X			   ; $82DF: BD 45 6E


; ============================================
; SECTION 2: CHARACTER PROCESSOR ($8AA5-$8B10)
; ============================================
;
; Main entry point for text character rendering
;

text_char_processor:
	LDA  current_char_raw	  ; $8AA5: A5 F6
	CMP  #$F0				  ; $8AA7: C9 F0
	BCS  control_dispatch	  ; $8AA9: B0 7D
	JSR  text_setup_90C4	   ; $8AAB: 20 C4 90
	JSR  text_init_vars		; $8AAE: 20 DA 8B
	LDA  #$00				  ; $8AB1: A9 00
	PHA						; $8AB3: 48
	JSR  text_func_9CCB		; $8AB4: 20 CB 9C
	JSR  text_func_9543		; $8AB7: 20 43 95
	JSR  text_read_loop		; $8ABA: 20 AF 95
	JSR  text_handler_95FF	 ; $8ABD: 20 FF 95
	JSR  text_func_963D		; $8AC0: 20 3D 96
	PLA						; $8AC3: 68
	CMP  #$03				  ; $8AC4: C9 03
	BEQ  $8ACB				 ; $8AC6: F0 03
	JSR  text_render_8F8C	  ; $8AC8: 20 8C 8F
	JSR  text_render_8FAA	  ; $8ACB: 20 AA 8F
	JSR  text_process_9022	 ; $8ACE: 20 22 90
	LDA  input_flags		   ; $8AD1: AD B4 07
	AND  #$08				  ; $8AD4: 29 08
	BEQ  $8AF7				 ; $8AD6: F0 1F
	LDA  text_flags_F5		 ; $8AD8: A5 F5
	AND  #$20				  ; $8ADA: 29 20
	BNE  $8AF2				 ; $8ADC: D0 14
	JSR  text_state_update	 ; $8ADE: 20 96 8C
	LDA  text_ppu_addr		 ; $8AE1: AD D4 03
	CLC						; $8AE4: 18
	ADC  #$20				  ; $8AE5: 69 20
	STA  text_ppu_addr		 ; $8AE7: 8D D4 03
	LDA  input_flags		   ; $8AEA: AD B4 07
	ORA  #$08				  ; $8AED: 09 08
	STA  input_flags		   ; $8AEF: 8D B4 07
	LDA  #$00				  ; $8AF2: A9 00
	JMP  $8AB3				 ; $8AF4: 4C B3 8A
	JSR  text_func_90F0		; $8AF7: 20 F0 90
	LDA  text_ppu_addr		 ; $8AFA: AD D4 03
	AND  #$1F				  ; $8AFD: 29 1F
	CMP  #$01				  ; $8AFF: C9 01
	BNE  $8AB3				 ; $8B01: D0 B0
	LDA  input_flags		   ; $8B03: AD B4 07
	BPL  text_control_check	; $8B06: 10 09
	LDA  current_char		  ; $8B08: A5 F8
	PHA						; $8B0A: 48
	JSR  text_state_update	 ; $8B0B: 20 96 8C
	PLA						; $8B0E: 68
	STA  current_char		  ; $8B0F: 85 F8


; ============================================
; SECTION 3: CONTROL CODE HANDLERS ($8B10-$8BA0)
; ============================================
;
; $FF = END, $FE = CTRL/PPU, $FD = LINE
;

	SED						; $8B10: F8
text_control_check:
	LDA  current_char		  ; $8B11: A5 F8
	CMP  #$F0				  ; $8B13: C9 F0
	BCC  $8B27				 ; $8B15: 90 10
	CMP  #$FF				  ; $8B17: C9 FF
	BEQ  $8B27				 ; $8B19: F0 0C
	CMP  #$FE				  ; $8B1B: C9 FE
	BEQ  $8B27				 ; $8B1D: F0 08
	CMP  #$FD				  ; $8B1F: C9 FD
control_type_check:
	BEQ  $8B27				 ; $8B21: F0 04
	LDA  #$F0				  ; $8B23: A9 F0
	STA  current_char		  ; $8B25: 85 F8
	RTS						; $8B27: 60
control_dispatch:
	CMP  #$FF				  ; $8B28: C9 FF
	BEQ  ctrl_FF_handler	   ; $8B2A: F0 37
	CMP  #$FE				  ; $8B2C: C9 FE
	BNE  ctrl_FD_handler	   ; $8B2E: D0 18
ctrl_FE_handler:
	ASL  text_ppu_addr		 ; $8B30: 0E D4 03
	ASL  text_ppu_addr		 ; $8B33: 0E D4 03
	ASL  text_ppu_addr		 ; $8B36: 0E D4 03
	LDA  text_param			; $8B39: A5 F7
	LSR						; $8B3B: 4A
	ROR  text_ppu_addr		 ; $8B3C: 6E D4 03
	LSR						; $8B3F: 4A
	ROR  text_ppu_addr		 ; $8B40: 6E D4 03
	LSR						; $8B43: 4A
	ROR  text_ppu_addr		 ; $8B44: 6E D4 03
	RTS						; $8B47: 60
ctrl_FD_handler:
	LDA  input_flags		   ; $8B48: AD B4 07
	AND  #$04				  ; $8B4B: 29 04
	BEQ  $8B60				 ; $8B4D: F0 11
	LDA  text_ppu_addr		 ; $8B4F: AD D4 03
	CLC						; $8B52: 18
	ADC  #$20				  ; $8B53: 69 20
	STA  text_ppu_addr		 ; $8B55: 8D D4 03
	LDA  input_flags		   ; $8B58: AD B4 07
	AND  #$FB				  ; $8B5B: 29 FB
	STA  input_flags		   ; $8B5D: 8D B4 07
	JMP  text_state_update	 ; $8B60: 4C 96 8C
ctrl_FF_handler:
	LDA  #$D1				  ; $8B63: A9 D1
	STA  text_var_04F2		 ; $8B65: 8D F2 04
	LDA  #$1E				  ; $8B68: A9 1E
	STA  text_var_04F3		 ; $8B6A: 8D F3 04
	LDA  #$0C				  ; $8B6D: A9 0C
	STA  text_var_03E1		 ; $8B6F: 8D E1 03
	LDA  text_var_03E1		 ; $8B72: AD E1 03
	ASL						; $8B75: 0A
	TAX						; $8B76: AA
	LDA  text_ptr_table,X	  ; $8B77: BD 6C 07
	ORA  text_ptr_table_hi,X   ; $8B7A: 1D 6D 07
	BEQ  $8BB6				 ; $8B7D: F0 37
	LDA  #$00				  ; $8B7F: A9 00
	STA  text_ptr_table,X	  ; $8B81: 9D 6C 07
	STA  text_ptr_table_hi,X   ; $8B84: 9D 6D 07
	LDA  #$0E				  ; $8B87: A9 0E
	STA  zp_loop_counter	   ; $8B89: 85 0D
	JSR  text_helper_8DD4	  ; $8B8B: 20 D4 8D
	LDA  zp_loop_counter	   ; $8B8E: A5 0D
	TAY						; $8B90: A8
	DEY						; $8B91: 88
	LDA  zp_temp_04			; $8B92: A5 04
	STA  text_array_04E0,Y	 ; $8B94: 99 E0 04
	LDA  zp_loop_counter	   ; $8B97: A5 0D
	ASL						; $8B99: 0A
	TAX						; $8B9A: AA
	LDA  zp_temp_00			; $8B9B: A5 00
	STA  $047E,X			   ; $8B9D: 9D 7E 04


; ============================================
; SECTION 4: TEXT READ LOOP ($95AF-$9650)
; ============================================
;
; Reads text from ($EE),Y pointer
;

text_read_loop:
	LDA  text_ppu_addr		 ; $95AF: AD D4 03
	AND  #$E0				  ; $95B2: 29 E0
	STA  text_ppu_addr		 ; $95B4: 8D D4 03
	LDA  text_var_03C9		 ; $95B7: AD C9 03
	AND  #$0F				  ; $95BA: 29 0F
	STA  text_var_03C9		 ; $95BC: 8D C9 03
	LDY  #$00				  ; $95BF: A0 00
	LDA  ($EE),Y			   ; $95C1: B1 EE
	STA  text_var_03C8		 ; $95C3: 8D C8 03
	AND  #$F0				  ; $95C6: 29 F0
	BNE  $95D1				 ; $95C8: D0 07
	LDA  ($EE),Y			   ; $95CA: B1 EE
	AND  #$0F				  ; $95CC: 29 0F
	JSR  text_helper_A4DE	  ; $95CE: 20 DE A4
	INC  text_offset		   ; $95D1: E6 F0
	LDY  #$01				  ; $95D3: A0 01
	LDA  ($EE),Y			   ; $95D5: B1 EE
	AND  #$F0				  ; $95D7: 29 F0
	ORA  text_var_03C9		 ; $95D9: 0D C9 03
	STA  text_var_03C9		 ; $95DC: 8D C9 03
	LDA  ($EE),Y			   ; $95DF: B1 EE
	PHA						; $95E1: 48
	AND  #$08				  ; $95E2: 29 08
	BEQ  $95ED				 ; $95E4: F0 07
	LSR						; $95E6: 4A
	LSR						; $95E7: 4A
	LSR						; $95E8: 4A
	LSR						; $95E9: 4A
	JSR  text_helper_A4E9	  ; $95EA: 20 E9 A4
	LDA  #$03				  ; $95ED: A9 03
	STA  text_var_03CB		 ; $95EF: 8D CB 03
	PLA						; $95F2: 68
	AND  #$04				  ; $95F3: 29 04
	BEQ  $95FE				 ; $95F5: F0 07
	LDY  #$02				  ; $95F7: A0 02
	LDA  ($EE),Y			   ; $95F9: B1 EE
	STA  text_var_03CB		 ; $95FB: 8D CB 03
	RTS						; $95FE: 60
text_handler_95FF:
	LDA  #$00				  ; $95FF: A9 00
	STA  text_x_pos			; $9601: 8D D6 03
	STA  text_y_pos			; $9604: 8D D7 03
	LDA  text_param			; $9607: A5 F7
	STA  text_window_id		; $9609: 8D DB 03
	LDA  #$00				  ; $960C: A9 00
	STA  $00F4				 ; $960E: 8D F4 00
	LDY  #$01				  ; $9611: A0 01
	LDA  ($EE),Y			   ; $9613: B1 EE
	AND  #$04				  ; $9615: 29 04
	BEQ  $961A				 ; $9617: F0 01
	INY						; $9619: C8
	STY  text_offset		   ; $961A: 84 F0
	LDA  text_var_04F2		 ; $961C: AD F2 04
	AND  #$0F				  ; $961F: 29 0F
	STA  text_var_04F2		 ; $9621: 8D F2 04
	LDA  text_var_03C9		 ; $9624: AD C9 03
	AND  #$F0				  ; $9627: 29 F0
	SEC						; $9629: 38
	SBC  #$01				  ; $962A: E9 01
	ORA  text_var_04F2		 ; $962C: 0D F2 04
	STA  text_var_04F2		 ; $962F: 8D F2 04
	LDA  #$FF				  ; $9632: A9 FF
	STA  text_state			; $9634: 8D D3 03
	LDA  #$10				  ; $9637: A9 10
	STA  text_var_04F3		 ; $9639: 8D F3 04
	RTS						; $963C: 60
text_func_963D:
	LDA  #$00				  ; $963D: A9 00
	STA  text_line_ctr		 ; $963F: 8D D9 03
	LDA  text_flags			; $9642: AD D5 03
	AND  #$F0				  ; $9645: 29 F0
	STA  text_flags			; $9647: 8D D5 03
	JSR  text_func_9349		; $964A: 20 49 93
	CMP  #$0F				  ; $964D: C9 0F
	BEQ  $967C				 ; $964F: F0 2B


; === END OF TEXT ENGINE ===
