#!/usr/bin/env python3
"""
Asset Reinserter for Dragon Warrior IV

Converts edited assets back to ROM format:
- JSON data tables → Assembly source code
- PNG graphics → CHR binary data
- Text files → Encoded dialog data
"""

import json
import struct
from pathlib import Path
from typing import Dict, Any, List, Optional

import click
from rich.console import Console

from tools import (
	ASSETS_DIR,
	SOURCE_DIR,
	PROJECT_ROOT,
)
from tools.asset_extractor import encode_text, DW4_TBL_REVERSE


class AssetReinserter:
	"""Converts extracted assets back to ASM source."""

	def __init__(self, assets_dir: Path, source_dir: Path):
		"""Initialize reinserter."""
		self.assets_dir = assets_dir
		self.source_dir = source_dir
		self.generated_dir = source_dir / "generated"
		self.console = Console()

	def setup_directories(self):
		"""Create output directory structure."""
		dirs = [
			self.generated_dir,
			self.generated_dir / "data",
			self.generated_dir / "text",
			self.generated_dir / "graphics",
		]
		for d in dirs:
			d.mkdir(parents=True, exist_ok=True)

	def convert_all(self):
		"""Convert all assets to ASM."""
		self.setup_directories()

		self.console.print("[bold]Converting assets to ASM...[/bold]")

		self.convert_monsters()
		self.convert_items()
		self.convert_spells()
		self.convert_text()

		self.console.print("\n[bold green]Asset conversion complete![/bold green]")

	def convert_monsters(self):
		"""Convert monster JSON to ASM."""
		json_path = self.assets_dir / "json" / "monsters" / "monsters.json"

		if not json_path.exists():
			self.console.print("[yellow]Warning: monsters.json not found[/yellow]")
			return

		with open(json_path, "r", encoding="utf-8") as f:
			data = json.load(f)

		# Generate ASM file
		asm_lines = [
			"; ============================================================================",
			"; Dragon Warrior IV - Monster Data",
			"; Generated by asset_reinserter.py - DO NOT EDIT DIRECTLY",
			"; Edit the JSON file and regenerate instead",
			"; ============================================================================",
			"",
			".alias MONSTER_COUNT $00  ; TODO: Set actual count",
			"",
			"MonsterTable:",
		]

		if "monsters" in data and data["monsters"]:
			for monster in data["monsters"]:
				# TODO: Generate actual monster data bytes
				asm_lines.append(f"\t; Monster {monster.get('id', '?')}: {monster.get('name', 'Unknown')}")
		else:
			asm_lines.append("\t; TODO: Monster data to be populated")

		asm_lines.append("")
		asm_lines.append("; End of monster data")

		output_path = self.generated_dir / "data" / "monsters.asm"
		with open(output_path, "w", encoding="utf-8", newline="\r\n") as f:
			f.write("\n".join(asm_lines))

		self.console.print(f"  Generated: {output_path.name}")

	def convert_items(self):
		"""Convert item JSON to ASM."""
		json_path = self.assets_dir / "json" / "items" / "items.json"

		if not json_path.exists():
			self.console.print("[yellow]Warning: items.json not found[/yellow]")
			return

		with open(json_path, "r", encoding="utf-8") as f:
			data = json.load(f)

		# Generate ASM file
		asm_lines = [
			"; ============================================================================",
			"; Dragon Warrior IV - Item Data",
			"; Generated by asset_reinserter.py - DO NOT EDIT DIRECTLY",
			"; ============================================================================",
			"",
			".alias ITEM_COUNT $00  ; TODO: Set actual count",
			"",
			"ItemTable:",
			"\t; TODO: Item data to be populated",
			"",
			"; End of item data",
		]

		output_path = self.generated_dir / "data" / "items.asm"
		with open(output_path, "w", encoding="utf-8", newline="\r\n") as f:
			f.write("\n".join(asm_lines))

		self.console.print(f"  Generated: {output_path.name}")

	def convert_spells(self):
		"""Convert spell JSON to ASM."""
		json_path = self.assets_dir / "json" / "spells" / "spells.json"

		if not json_path.exists():
			self.console.print("[yellow]Warning: spells.json not found[/yellow]")
			return

		# Generate ASM file
		asm_lines = [
			"; ============================================================================",
			"; Dragon Warrior IV - Spell Data",
			"; Generated by asset_reinserter.py - DO NOT EDIT DIRECTLY",
			"; ============================================================================",
			"",
			".alias SPELL_COUNT $00  ; TODO: Set actual count",
			"",
			"SpellTable:",
			"\t; TODO: Spell data to be populated",
			"",
			"; End of spell data",
		]

		output_path = self.generated_dir / "data" / "spells.asm"
		with open(output_path, "w", encoding="utf-8", newline="\r\n") as f:
			f.write("\n".join(asm_lines))

		self.console.print(f"  Generated: {output_path.name}")

	def convert_text(self):
		"""Convert text JSON to ASM."""
		json_path = self.assets_dir / "text" / "dialog.json"

		if not json_path.exists():
			self.console.print("[yellow]Warning: dialog.json not found[/yellow]")
			return

		# Generate ASM file
		asm_lines = [
			"; ============================================================================",
			"; Dragon Warrior IV - Dialog Text",
			"; Generated by asset_reinserter.py - DO NOT EDIT DIRECTLY",
			"; ============================================================================",
			"",
			"DialogTable:",
			"\t; TODO: Dialog data to be populated",
			"",
			"; End of dialog data",
		]

		output_path = self.generated_dir / "text" / "dialog.asm"
		with open(output_path, "w", encoding="utf-8", newline="\r\n") as f:
			f.write("\n".join(asm_lines))

		self.console.print(f"  Generated: {output_path.name}")

	def json_to_asm_bytes(self, data: List[int], label: str, bytes_per_line: int = 16) -> List[str]:
		"""Convert a list of bytes to ASM .byte statements."""
		lines = [f"{label}:"]

		for i in range(0, len(data), bytes_per_line):
			chunk = data[i:i + bytes_per_line]
			hex_values = ", ".join(f"${b:02x}" for b in chunk)
			lines.append(f"\t.byte {hex_values}")

		return lines


@click.group()
def cli():
	"""Dragon Warrior IV Asset Reinserter."""
	pass


@cli.command()
@click.option("--assets", "-a", default=str(ASSETS_DIR), help="Assets directory")
@click.option("--source", "-s", default=str(SOURCE_DIR), help="Source output directory")
def convert(assets: str, source: str):
	"""Convert all assets to ASM source."""
	reinserter = AssetReinserter(Path(assets), Path(source))
	reinserter.convert_all()


if __name__ == "__main__":
	cli()
